{{- $relname := .Release.Name -}}
{{- $chartname := .Chart.Name -}}
{{- $chartver := .Chart.Version -}}
{{- $containerport := .Values.resources.containerPort -}}
{{- $fullname := .Release.Name | trunc 24 -}}
{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | trunc 24 }}
  labels:
    app: {{ $fullname }}
    chart: "{{ $relname }}-{{ $chartver | replace "+" "_" }}"
    release: "{{ $relname }}"
  {{- if .useLbex }}
  annotations:
    "kubernetes.io/loadbalancer-class": "loadbalancer-lbex"
    "loadbalancer-port.lbex/{{ $fullname }}": "{{ .lbexPort}}"
  {{- end }}
spec:
  {{- if .useLbex }}
  type: NodePort
  {{- else if .type}}
  type: {{ .type }}
  {{- end }}
  ports:
  - name: {{ $fullname }}
    port: {{ $containerport }}
    {{- if or (.useLbex) (eq .type "NodePort") }}
    {{- if .nodeport }}
    nodePort: {{ .nodeport }}
    {{- end }}
    {{- end }}
  selector:
    app: {{ $fullname }}
{{- end }}